## IMPORT DA(S) BIBLIOTECA(S)

In [64]:
import pandas as pd

## FAZENDO A LEITURA DA PLANILHA

In [65]:
df_movi_func = pd.read_csv("Movimentacoes_Consolidado_Finalizado.csv", encoding="utf-8", sep=";")

df_movi_func.head(15)

,data,descricaoFuncionarioCargo,descricaoFuncionarioEscalaTrabalho,descricaoFuncionarioSindicato,descricaoPostoTrabalho,matricula
0,01/02/2026,SUPERVISOR,"SEG,TER,QUA,QUI,SEX - 07:00:00-16:00:00",ANVISA REC,ANVISA REC - SUPERVISOR,1991
1,01/02/2026,ATENDENTE,"SEG,TER,QUA,QUI,SEX - 07:00:00-13:00:00",ANVISA REC,ANVISA REC - ATENDENTE,1999
2,01/02/2026,ATENDENTE,"SEG,TER,QUA,QUI,SEX - 13:00:00-19:00:00",ANVISA REC,ANVISA REC - ATENDENTE,3440
3,01/02/2026,ATENDENTE,"SEG,TER,QUA,QUI,SEX - 07:00:00-13:00:00",ANVISA REC,ANVISA REC - ATENDENTE,1992
4,01/02/2026,ATENDENTE,"SEG,TER,QUA,QUI,SEX - 07:00:00-13:00:00",ANVISA REC,ANVISA REC - ATENDENTE,2295
5,01/02/2026,ATENDENTE,"SEG,TER,QUA,QUI,SEX - 07:00:00-13:00:00",ANVISA REC,ANVISA REC - ATENDENTE,2493
6,01/02/2026,DIGITALIZADOR,"SEG,TER,QUA,QUI,SEX - 13:00:00-19:00:00",CAESB (GDOC),CAESB GDOC - DIGITALIZADOR,3648
7,01/02/2026,DIGITALIZADOR,"SEG,TER,QUA,QUI,SEX - 13:00:00-19:00:00",CAESB (GDOC),CAESB GDOC - DIGITALIZADOR,2356
8,01/02/2026,DIGITALIZADOR,"SEG,TER,QUA,QUI,SEX - 13:00:00-19:00:00",CAESB (GDOC),CAESB GDOC - DIGITALIZADOR,2337
9,01/02/2026,DIGITALIZADOR,"SEG,TER,QUA,QUI,SEX - 07:00:00-13:00:00",CAESB (GDOC),CAESB GDOC - DIGITALIZADOR,3536
10,01/02/2026,DIGITALIZADOR,"SEG,TER,QUA,QUI,SEX - 07:00:00-13:00:00",CAESB (GDOC),CAESB GDOC - DIGITALIZADOR,2328
11,01/02/2026,DIGITALIZADOR,"SEG,TER,QUA,QUI,SEX - 13:00:00-19:00:00",CAESB (GDOC),CAESB GDOC - DIGITALIZADOR,3332
12,01/02/2026,DIGITALIZADOR,"SEG,TER,QUA,QUI,SEX - 07:00:00-13:00:00",CAESB (GDOC),CAESB GDOC - DIGITALIZADOR,2325
13,01/02/2026,DIGITALIZADOR,"SEG,TER,QUA,QUI,SEX - 07:00:00-13:00:00",CAESB (GDOC),CAESB GDOC - DIGITALIZADOR,2298
14,01/02/2026,DIGITALIZADOR,"SEG,TER,QUA,QUI,SEX - 13:00:00-19:00:00",CAESB (GDOC),CAESB GDOC - DIGITALIZADOR,3533

## IDENTIFICAR OS TIPOS DE DADOS NA PLANILHAS

In [66]:
df_movi_func.info()

<class 'pandas.DataFrame'>
RangeIndex: 463 entries, 0 to 462
Data columns (total 6 columns):
 #   Column                              Non-Null Count  Dtype
---  ------                              --------------  -----
 0   data                                463 non-null    str
 1   descricaoFuncionarioCargo           463 non-null    str
 2   descricaoFuncionarioEscalaTrabalho  463 non-null    str
 3   descricaoFuncionarioSindicato       463 non-null    str
 4   descricaoPostoTrabalho              463 non-null    str
 5   matricula                           463 non-null    int64
dtypes: int64(1), str(5)
memory usage: 66.4 KB

## FOI OBSERVADO QUE O CAMPO "data" ESTÁ EM str(string) - TRANSFORMAR EM FORMATO DE DATA

In [67]:
df_movi_func["data"] = pd.to_datetime(df_movi_func["data"], format="%d/%m/%Y")

df_movi_func.info()

<class 'pandas.DataFrame'>
RangeIndex: 463 entries, 0 to 462
Data columns (total 6 columns):
 #   Column                              Non-Null Count  Dtype
---  ------                              --------------  -----
 0   data                                463 non-null    datetime64[us]
 1   descricaoFuncionarioCargo           463 non-null    str
 2   descricaoFuncionarioEscalaTrabalho  463 non-null    str
 3   descricaoFuncionarioSindicato       463 non-null    str
 4   descricaoPostoTrabalho              463 non-null    str
 5   matricula                           463 non-null    int64
dtypes: datetime64[us](1), int64(1), str(4)
memory usage: 61.9 KB

## REALIZAR ALGUNS FILTROS NA PLANILHA

In [68]:
ft_cargo = df_movi_func[df_movi_func["descricaoFuncionarioSindicato"] == "CAESB (GDOC)"]

ft_escala = df_movi_func[df_movi_func["descricaoFuncionarioEscalaTrabalho"] == "SEG,TER,QUA,QUI,SEX - 07:00:00-13:00:00"]

ft_cargo_escala = df_movi_func[
    (df_movi_func["descricaoFuncionarioSindicato"].isin(["ANVISA REC", "CAESB (GDOC)"])) 
    & (df_movi_func["descricaoFuncionarioEscalaTrabalho"] == "SEG,TER,QUA,QUI,SEX - 07:00:00-13:00:00")
    ]

#ft_cargo.head(50)
#ft_escala.head(100)
ft_cargo_escala.head(100)

,data,descricaoFuncionarioCargo,descricaoFuncionarioEscalaTrabalho,descricaoFuncionarioSindicato,descricaoPostoTrabalho,matricula
1,2026-02-01,ATENDENTE,"SEG,TER,QUA,QUI,SEX - 07:00:00-13:00:00",ANVISA REC,ANVISA REC - ATENDENTE,1999
3,2026-02-01,ATENDENTE,"SEG,TER,QUA,QUI,SEX - 07:00:00-13:00:00",ANVISA REC,ANVISA REC - ATENDENTE,1992
4,2026-02-01,ATENDENTE,"SEG,TER,QUA,QUI,SEX - 07:00:00-13:00:00",ANVISA REC,ANVISA REC - ATENDENTE,2295
5,2026-02-01,ATENDENTE,"SEG,TER,QUA,QUI,SEX - 07:00:00-13:00:00",ANVISA REC,ANVISA REC - ATENDENTE,2493
9,2026-02-01,DIGITALIZADOR,"SEG,TER,QUA,QUI,SEX - 07:00:00-13:00:00",CAESB (GDOC),CAESB GDOC - DIGITALIZADOR,3536
10,2026-02-01,DIGITALIZADOR,"SEG,TER,QUA,QUI,SEX - 07:00:00-13:00:00",CAESB (GDOC),CAESB GDOC - DIGITALIZADOR,2328
12,2026-02-01,DIGITALIZADOR,"SEG,TER,QUA,QUI,SEX - 07:00:00-13:00:00",CAESB (GDOC),CAESB GDOC - DIGITALIZADOR,2325
13,2026-02-01,DIGITALIZADOR,"SEG,TER,QUA,QUI,SEX - 07:00:00-13:00:00",CAESB (GDOC),CAESB GDOC - DIGITALIZADOR,2298
17,2026-02-01,SUPERVISOR,"SEG,TER,QUA,QUI,SEX - 07:00:00-13:00:00",CAESB (GDOC),CAESB GDOC - SUPERVISOR INTERPRETE,3426
19,2026-02-01,SUPERVISOR,"SEG,TER,QUA,QUI,SEX - 07:00:00-13:00:00",CAESB (GDOC),CAESB GDOC - SUPERVISOR INTERPRETE,2311
21,2026-02-01,CONTROLE DE QUALIDADE,"SEG,TER,QUA,QUI,SEX - 07:00:00-13:00:00",CAESB (GDOC),CAESB GDOC - CONTROLE DE QUALIDADE,2316
22,2026-02-01,CONTROLE DE QUALIDADE,"SEG,TER,QUA,QUI,SEX - 07:00:00-13:00:00",CAESB (GDOC),CAESB GDOC - CONTROLE DE QUALIDADE,2342
23,2026-02-01,CONTROLE DE QUALIDADE,"SEG,TER,QUA,QUI,SEX - 07:00:00-13:00:00",CAESB (GDOC),CAESB GDOC - CONTROLE DE QUALIDADE,2321
24,2026-02-01,CONTROLE DE QUALIDADE,"SEG,TER,QUA,QUI,SEX - 07:00:00-13:00:00",CAESB (GDOC),CAESB GDOC - CONTROLE DE QUALIDADE,2347
25,2026-02-01,PREPARADOR,"SEG,TER,QUA,QUI,SEX - 07:00:00-13:00:00",CAESB (GDOC),CAESB GDOC - PREPARADOR,2335
27,2026-02-01,PREPARADOR,"SEG,TER,QUA,QUI,SEX - 07:00:00-13:00:00",CAESB (GDOC),CAESB GDOC - PREPARADOR,2333
28,2026-02-01,PREPARADOR,"SEG,TER,QUA,QUI,SEX - 07:00:00-13:00:00",CAESB (GDOC),CAESB GDOC - PREPARADOR,2306
29,2026-02-01,PREPARADOR,"SEG,TER,QUA,QUI,SEX - 07:00:00-13:00:00",CAESB (GDOC),CAESB GDOC - PREPARADOR,2348
31,2026-02-01,PREPARADOR,"SEG,TER,QUA,QUI,SEX - 07:00:00-13:00:00",CAESB (GDOC),CAESB GDOC - PREPARADOR,2307
32,2026-02-01,PREPARADOR,"SEG,TER,QUA,QUI,SEX - 07:00:00-13:00:00",CAESB (GDOC),CAESB GDOC - PREPARADOR,2338
35,2026-02-01,PREPARADOR,"SEG,TER,QUA,QUI,SEX - 07:00:00-13:00:00",CAESB (GDOC),CAESB GDOC - PREPARADOR,2300
36,2026-02-01,PREPARADOR,"SEG,TER,QUA,QUI,SEX - 07:00:00-13:00:00",CAESB (GDOC),CAESB GDOC - PREPARADOR,2349
41,2026-02-01,ARQUIVISTA,"SEG,TER,QUA,QUI,SEX - 07:00:00-13:00:00",CAESB (GDOC),CAESB GDOC - ARQUIVISTA,3104
43,2026-02-01,CLASSIFICADOR,"SEG,TER,QUA,QUI,SEX - 07:00:00-13:00:00",CAESB (GDOC),CAESB GDOC - CLASSIFICADOR,2301
45,2026-02-01,CLASSIFICADOR,"SEG,TER,QUA,QUI,SEX - 07:00:00-13:00:00",CAESB (GDOC),CAESB GDOC - CLASSIFICADOR,2845
46,2026-02-01,CLASSIFICADOR,"SEG,TER,QUA,QUI,SEX - 07:00:00-13:00:00",CAESB (GDOC),CAESB GDOC - CLASSIFICADOR,2314
48,2026-02-01,CLASSIFICADOR,"SEG,TER,QUA,QUI,SEX - 07:00:00-13:00:00",CAESB (GDOC),CAESB GDOC - CLASSIFICADOR,2334
53,2026-02-01,CLASSIFICADOR,"SEG,TER,QUA,QUI,SEX - 07:00:00-13:00:00",CAESB (GDOC),CAESB GDOC - CLASSIFICADOR,2317
56,2026-02-01,CLASSIFICADOR,"SEG,TER,QUA,QUI,SEX - 07:00:00-13:00:00",CAESB (GDOC),CAESB GDOC - CLASSIFICADOR,2351
58,2026-02-01,CLASSIFICADOR,"SEG,TER,QUA,QUI,SEX - 07:00:00-13:00:00",CAESB (GDOC),CAESB GDOC - CLASSIFICADOR,2853
59,2026-02-01,CLASSIFICADOR,"SEG,TER,QUA,QUI,SEX - 07:00:00-13:00:00",CAESB (GDOC),CAESB GDOC - CLASSIFICADOR,2350

In [69]:
df_movi_func.info()

<class 'pandas.DataFrame'>
RangeIndex: 463 entries, 0 to 462
Data columns (total 6 columns):
 #   Column                              Non-Null Count  Dtype
---  ------                              --------------  -----
 0   data                                463 non-null    datetime64[us]
 1   descricaoFuncionarioCargo           463 non-null    str
 2   descricaoFuncionarioEscalaTrabalho  463 non-null    str
 3   descricaoFuncionarioSindicato       463 non-null    str
 4   descricaoPostoTrabalho              463 non-null    str
 5   matricula                           463 non-null    int64
dtypes: datetime64[us](1), int64(1), str(4)
memory usage: 61.9 KB

## SALNDO A PLANILHA COM A TRONSFORMAÇÃO E FILTRO

In [70]:
ft_cargo_escala.to_csv("Movimentacoes_Consolidadas_Filtradas.csv", index=False, encoding= "utf-8", sep=";")